// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn0GbpoG-7zSCPIe9HVcY5m2H9FweWGDU',
    appId: '1:1058782957318:web:b16f83a6f2012af3291887',
    messagingSenderId: '1058782957318',
    projectId: 'finote-db',
    authDomain: 'finote-db.firebaseapp.com',
    storageBucket: 'finote-db.firebasestorage.app',
    measurementId: 'G-1CVF8LM1F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfzRnqm-yUPXjVwPBpQIG88WrN50iOvag',
    appId: '1:1058782957318:android:adaf46d79b1708bd291887',
    messagingSenderId: '1058782957318',
    projectId: 'finote-db',
    storageBucket: 'finote-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5dq5lBJ1g6Hw5dm8zrO36bJQbiuoIfEA',
    appId: '1:1058782957318:ios:555158d4e6d9663a291887',
    messagingSenderId: '1058782957318',
    projectId: 'finote-db',
    storageBucket: 'finote-db.firebasestorage.app',
    iosBundleId: 'com.example.apkKeuangan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5dq5lBJ1g6Hw5dm8zrO36bJQbiuoIfEA',
    appId: '1:1058782957318:ios:555158d4e6d9663a291887',
    messagingSenderId: '1058782957318',
    projectId: 'finote-db',
    storageBucket: 'finote-db.firebasestorage.app',
    iosBundleId: 'com.example.apkKeuangan',
  );
}
